$lock_bg = rgba(249, 245, 215, 1.0)
$lock_accent = rgb(b57614)
$lock_muted = rgb(7c6f64)
$lock_text = rgb(3c3836)
$lock_outer = rgba(b57614ee) rgba(d79921ee) 45deg
$lock_check = rgba(98971aee) rgba(689d6aee) 120deg
$lock_fail = rgba(cc241dee) rgba(af3a03ee) 40deg
