hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("~/.config/waybar/launch.sh")
    hl.exec_cmd("swaync")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("sleep 1 && ~/.config/hypr/scripts/theme-switch.sh $(cat ${XDG_CACHE_HOME:-$HOME/.cache}/dotfiles/theme/mode 2>/dev/null || printf dark)")
end)
