require'trash.plugins'
require'trash.mappings'
require'trash.lsp'
require'trash.lspsaga'
require'trash.telescope'
require'trash.cmp'
require'trash.treesitter'
require'trash.lualine'
require'trash.bufferline'
-- require'trash.navigator'
